apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.rootPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.secret.dbName | b64enc | quote }}
  MYSQL_USER: {{ .Values.mysql.secret.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.secret.password | b64enc | quote }}