apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.secret.dbHost | b64enc | quote }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.secret.dbUser | b64enc | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.secret.dbPassword | b64enc | quote }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.secret.dbName | b64enc | quote }}