apiVersion: v1
kind: ServiceAccount
metadata:
  name: diagnostic-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: diagnostic-rb
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: diagnostic-sa
  namespace: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: diagnostic-pod
  namespace: dev
spec:
  serviceAccountName: diagnostic-sa
  containers:
  - name: diagnostic
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "=== Проверка работы NetworkPolicy ==="
        echo "Пытаемся подключиться к MySQL (порт 3306)"
        echo

        apk add --no-cache netcat-openbsd

        nc -z -w 5 mysql.dev.svc.cluster.local 3306 && echo "Подключение УСПЕШНО (NetworkPolicy НЕ работает!)" || echo "Подключение ОТКЛОНЕНО (NetworkPolicy работает как надо!)"

        echo
        echo "=== Поды WordPress ==="

        apk add --no-cache curl

        curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"

        chmod +x kubectl
        ./kubectl get pods -n dev -l app=wordpress -o wide

        echo
        echo "Диагностика завершена"
        sleep infinity
  restartPolicy: Never