Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.10"
    dev.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y python3 openssh-server
      mkdir -p /root/.ssh
      cat /vagrant/id_rsa.pub >> /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.11"
    prod.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y python3 openssh-server
      mkdir -p /root/.ssh
      until [ -f /vagrant/id_rsa.pub ]; do sleep 1; done
      cat /vagrant/id_rsa.pub >> /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
    SHELL
  end
end
