Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"  #
  #config.ssh.private_key_path = "~/.ssh/id_rsa"
  #config.ssh.forward_agent = true


 # Настройка для клиента
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip:"192.168.22.21"  
    client.vm.provider "virtualbox" do |vb|
      vb.name = "client-vm"
      vb.memory = "1024" 
       
	
    client.vm.provision "shell", inline: <<-SHELL
       if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
	sudo -u vagrant ssh-keygen -t rsa -f /home/vagrant/.ssh/id_rsa -N ""
	chmod 600 /home/vagrant/.ssh/id_rsa
	chmod 600 /home/vagrant/.ssh/id_rsa.pub
	chmod 700 /home/vagrant/.ssh
	fi
	cp /home/vagrant/.ssh/id_rsa.pub /vagrant/
	
	SHELL
    end
   
	client.vm.provision "shell", inline: 'echo "192.168.22.20 server" | sudo tee -a /etc/hosts'	 #path: "provision_client.sh"
	end
   


  # Настройка для сервера
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip:"192.168.22.20"  
    server.vm.provider "virtualbox" do |vb|
      vb.name = "server-vm"
      vb.memory = "1024"  
	end
	server.vm.provision "file", source: "D:/vagrantmm/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
	server.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
	chmod 600 /home/vagrant/.ssh/authorized_keys
	chmod 700 /home/vagrant/.ssh
	SHELL
	
	end
	

 end